SMsystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(('user.urls', 'apps'), namespace='user')),
    path('order/', include(('order.urls', 'apps'), namespace='order')),
    path('', include(('goods.urls', 'apps'), namespace='goods')),
    path('customer/', include(('customer.urls', 'apps'), namespace='customer')),
]

apps/customer/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import CustomerListView, CustomerInsertView, CustomerDelView, CustomerUpdateView, CustomerInfoView, CustomerDelListView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('customer_list/', login_required(CustomerListView.as_view()), name='List'),
    path('customer_insert/',login_required(CustomerInsertView.as_view()), name='insert'),
    path('customer_del/', login_required(CustomerDelView.as_view()), name='delete'),
    path('customer_update/', login_required(CustomerUpdateView.as_view()), name='update'),
    path('customer_info/', login_required(CustomerInfoView.as_view()), name='info'),
    path('customer_dellist/', login_required(CustomerDelListView.as_view()), name='delList')
]

apps/goods/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import IndexView, GoodsShowView, WelcomeView, GoodsUpdateStatus, GoodsDeleteView, GoodsInsertView, GoodsImgUpView, GoodsUpdateInfoView
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', login_required(IndexView.as_view()), name='index'),
    path('show/', login_required(GoodsShowView.as_view()), name='show'),
    path('welcome/', login_required(WelcomeView.as_view()), name='welcome'),
    path('GoodsUpdateStatus/', login_required(GoodsUpdateStatus.as_view()), name='updateStatus'),
    path('GoodsDeleteView/', login_required(GoodsDeleteView.as_view()), name='deleteGoods'),
    path('GoodsInsertView/', login_required(GoodsInsertView.as_view()), name='insertGoods'),
    path('GoodsImgUpView', login_required(GoodsImgUpView.as_view()), name='imgUp'),
    path('goods_update/', login_required(GoodsUpdateInfoView.as_view()), name='updateGoods')

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/order/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import OrderListView, OrderInsertView, OrderDelView, OrderInfoView, OrderDelListView, OrderSearchByDateView,CountChartsView

urlpatterns = [
    path('order_list/', login_required(OrderListView.as_view()), name='list'),
    path('order_insert/', login_required(OrderInsertView.as_view()), name='insert'),
    path('order_delete/', login_required(OrderDelView.as_view()), name='delete'),
    path('order_info/', login_required(OrderInfoView.as_view()), name='info'),
    path('order_del_list/', login_required(OrderDelListView.as_view()), name='del_list'),
    path('order_search_date/', login_required(OrderSearchByDateView.as_view()), name='date_search'),
    path('order_count_charts/', login_required(CountChartsView.as_view()), name='count_charts')
]

apps/user/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import LoginView, MemberShowView, LoginOutView, ReSetPasswordView, ReSetPwdView,LoginFailView

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('membershow/', login_required(MemberShowView.as_view()), name='membershow'),
    path('loginout/', login_required(LoginOutView.as_view()), name='loginout'),
    path('login_reset_password/', ReSetPasswordView.as_view(), name='reset'),
    path('login_reset_pwd/<token>', ReSetPwdView.as_view(), name='reset_pwd'),
    path('login_fail/', LoginFailView.as_view(), name='login_fail')
]

templates/index.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<link rel="Bookmark" href="{% static 'favicon.ico'%}" >
<link rel="Shortcut Icon" href="{% static 'favicon.ico'%}" />

<script type="text/javascript" src="{% static 'lib/html5shiv.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/respond.min.js' %}"></script>

<link rel="stylesheet" type="text/css" href="{% static 'h-ui/css/H-ui.min.css'%}" />
<link rel="stylesheet" type="text/css" href="{% static 'h-ui.admin/css/H-ui.admin.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'lib/Hui-iconfont/1.0.8/iconfont.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'h-ui.admin/skin/default/skin.css' %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static 'h-ui.admin/css/style.css' %}" />
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>H-ui.admin v3.1</title>
<meta name="keywords" content="H-ui.admin v3.1,H-ui网站后台模版,后台模版下载,后台管理系统模版,HTML后台模版下载">
<meta name="description" content="H-ui.admin v3.1，是一款由国人开发的轻量级扁平化网站后台模板，完全免费开源的网站后台管理系统模版，适合中小型CMS后台系统。">
</head>
<body>
<header class="navbar-wrapper">
	<div class="navbar navbar-fixed-top">
		<div class="container-fluid cl"> <a class="logo navbar-logo f-l mr-10 hidden-xs" href="/aboutHui.shtml">H-ui.admin</a> <a class="logo navbar-logo-m f-l mr-10 visible-xs" href="/aboutHui.shtml">H-ui</a> 
			<span class="logo navbar-slogan f-l mr-10 hidden-xs">v3.1</span> 
			<a aria-hidden="false" class="nav-toggle Hui-iconfont visible-xs" href="javascript:;">&#xe667;</a>
			<nav class="nav navbar-nav">
				<ul class="cl">
					<li class="dropDown dropDown_hover"><a href="javascript:;" class="dropDown_A"><i class="Hui-iconfont">&#xe600;</i> 新增 <i class="Hui-iconfont">&#xe6d5;</i></a>
						<ul class="dropDown-menu menu radius box-shadow">
							<li><a href="javascript:;" onclick="article_add('添加资讯','article-add.html')"><i class="Hui-iconfont">&#xe616;</i> 资讯</a></li>
							<li><a href="javascript:;" onclick="picture_add('添加资讯','picture-add.html')"><i class="Hui-iconfont">&#xe613;</i> 图片</a></li>
							<li><a href="javascript:;" onclick="product_add('添加资讯','product-add.html')"><i class="Hui-iconfont">&#xe620;</i> 产品</a></li>
							<li><a href="javascript:;" onclick="member_add('添加用户','member-add.html','','510')"><i class="Hui-iconfont">&#xe60d;</i> 用户</a></li>
					</ul>
				</li>
			</ul>
		</nav>
		<nav id="Hui-userbar" class="nav navbar-nav navbar-userbar hidden-xs">
			<ul class="cl">
				<li>欢迎您！</li>
				<li class="dropDown dropDown_hover">
					<a href="#" class="dropDown_A">{{ user.username }} <i class="Hui-iconfont">&#xe6d5;</i></a>
					<ul class="dropDown-menu menu radius box-shadow">
						<li><a href="javascript:;" onClick="member_show('admin','{% url 'user:membershow' %}','500','630')">个人信息</a></li>
						<li><a href="#">切换账户</a></li>
						<li><a href="{% url 'user:loginout' %}">退出</a></li>
				</ul>
			</li>
				<li id="Hui-msg"> <a href="#" title="消息"><span class="badge badge-danger">1</span><i class="Hui-iconfont" style="font-size:18px">&#xe68a;</i></a> </li>
				<li id="Hui-skin" class="dropDown right dropDown_hover"> <a href="javascript:;" class="dropDown_A" title="换肤"><i class="Hui-iconfont" style="font-size:18px">&#xe62a;</i></a>
					<ul class="dropDown-menu menu radius box-shadow">
						<li><a href="javascript:;" data-val="default" title="默认（黑色）">默认（黑色）</a></li>
						<li><a href="javascript:;" data-val="blue" title="蓝色">蓝色</a></li>
						<li><a href="javascript:;" data-val="green" title="绿色">绿色</a></li>
						<li><a href="javascript:;" data-val="red" title="红色">红色</a></li>
						<li><a href="javascript:;" data-val="yellow" title="黄色">黄色</a></li>
						<li><a href="javascript:;" data-val="orange" title="橙色">橙色</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>
</div>
</header>
<aside class="Hui-aside">
	<div class="menu_dropdown bk_2">

		<dl id="menu-product">
			<dt><i class="Hui-iconfont">&#xe620;</i> 产品管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'goods:show' %}" data-title="产品管理" href="javascript:void(0)">产品管理</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-comments">
			<dt><i class="Hui-iconfont">&#xe623;</i> 订单管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'order:list'%}" data-title="订单列表" href="javascript:;">订单列表</a></li>
					<li><a data-href="{% url 'order:del_list' %}" data-title="删除的订单" href="javascript:void(0)">删除的订单</a></li>
			</ul>
		</dd>
	</dl>
		<dl id="menu-member">
			<dt><i class="Hui-iconfont">&#xe60d;</i> 客户管理<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="{% url 'customer:List'%}" data-title="会员列表" href="javascript:;">客户列表</a></li>
					<li><a data-href="{% url 'customer:delList'%}" data-title="删除的会员" href="javascript:;">删除的客户</a></li>
			</ul>
		</dd>
	</dl>

		<dl id="menu-tongji">
			<dt><i class="Hui-iconfont">&#xe61a;</i> 销售统计<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>

					<li><a data-href="{% url 'order:count_charts' %}" data-title="柱状图" href="javascript:void(0)">统计图</a></li>

			</ul>
		</dd>
	</dl>
		<dl id="menu-system">
			<dt><i class="Hui-iconfont">&#xe62e;</i> 用户相关<i class="Hui-iconfont menu_dropdown-arrow">&#xe6d5;</i></dt>
			<dd>
				<ul>
					<li><a data-href="system-base.html" data-title="系统设置" href="javascript:void(0)">系统设置</a></li>
					<li><a data-href="system-category.html" data-title="栏目管理" href="javascript:void(0)">栏目管理</a></li>
					<li><a data-href="system-data.html" data-title="数据字典" href="javascript:void(0)">数据字典</a></li>
					<li><a data-href="system-shielding.html" data-title="屏蔽词" href="javascript:void(0)">屏蔽词</a></li>
					<li><a data-href="system-log.html" data-title="系统日志" href="javascript:void(0)">系统日志</a></li>
			</ul>
		</dd>
	</dl>
</div>
</aside>
<div class="dislpayArrow hidden-xs"><a class="pngfix" href="javascript:void(0);" onClick="displaynavbar(this)"></a></div>
<section class="Hui-article-box">
	<div id="Hui-tabNav" class="Hui-tabNav hidden-xs">
		<div class="Hui-tabNav-wp">
			<ul id="min_title_list" class="acrossTab cl">
				<li class="active">
					<span title="我的桌面" data-href="{% url 'goods:welcome' %}">我的桌面</span>
					<em></em></li>
		</ul>
	</div>
		<div class="Hui-tabNav-more btn-group"><a id="js-tabNav-prev" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d4;</i></a><a id="js-tabNav-next" class="btn radius btn-default size-S" href="javascript:;"><i class="Hui-iconfont">&#xe6d7;</i></a></div>
</div>
	<div id="iframe_box" class="Hui-article">
		<div class="show_iframe">
			<div style="display:none" class="loading"></div>
			<iframe scrolling="yes" frameborder="0" src="{% url 'goods:welcome' %}"></iframe>
	</div>
</div>
</section>

<div class="contextMenu" id="Huiadminmenu">
	<ul>
		<li id="closethis">关闭当前 </li>
		<li id="closeall">关闭全部 </li>
</ul>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static 'lib/jquery/1.9.1/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/layer/2.4/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'h-ui/js/H-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'h-ui.admin/js/H-ui.admin.js' %}"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="{% static 'lib/jquery.contextmenu/jquery.contextmenu.r2.js' %}"></script>
<script type="text/javascript">
$(function(){
	/*$("#min_title_list li").contextMenu('Huiadminmenu', {
		bindings: {
			'closethis': function(t) {
				console.log(t);
				if(t.find("i")){
					t.find("i").trigger("click");
				}		
			},
			'closeall': function(t) {
				alert('Trigger was '+t.id+'\nAction was Email');
			},
		}
	});*/
});
/*个人信息*/
function myselfinfo(){
	layer.open({
		type: 1,
		area: ['360px','400px'],
		fix: false, //不固定
		maxmin: true,
		shade:0.4,
		title: '查看信息',
		content: '<div>管理员信息</div>'
	});
}

/*资讯-添加*/
function article_add(title,url){
	var index = layer.open({
		type: 2,
		title: title,
		content: url
	});
	layer.full(index);
}
/*图片-添加*/
function picture_add(title,url){
	var index = layer.open({
		type: 2,
		title: title,
		content: url
	});
	layer.full(index);
}
/*产品-添加*/
function product_add(title,url){
	var index = layer.open({
		type: 2,
		title: title,
		content: url
	});
	layer.full(index);
}
/*用户-添加*/
function member_add(title,url,w,h){
	layer_show(title,url,w,h);
}
{#个人信息查看#}
function member_show(title,url,w,h){
	layer_show(title,url,w,h);
}

</script> 


</body>
</html>

templates/login.html
{% load staticfiles %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>登录</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/body1.css' %}"/>
</head>
<body>

{{ errmsg }}
<div class="container">
	<section id="content">
		<form method="post">
            {% csrf_token %}
			<h1>会员登录</h1>
			<div>
				<input type="text" placeholder="用户名" required="" id="username" name="username" onkeyup="value=value.replace(/[\u4E00-\u9FA5]/g,'')"/>
			</div>
			<div>
				<input type="password" placeholder="密码" required="" id="pwd" name="pwd"/>
			</div>
			 <div class="">
				<span class="help-block u-errormessage" id="js-server-helpinfo">&nbsp;</span>			</div>
			<div>
				<!-- <input type="submit" value="Log in" /> -->
				<input type="submit" value="登录" class="btn btn-primary" id="js-btn-login"/>
				<a href="#" onclick="password_reset('忘记密码?','{% url 'user:reset'%}','400','500')">忘记密码?</a>
				<!-- <a href="#">Register</a> -->
			</div>
		</form><!-- form -->
		 <div class="button">
			<span class="help-block u-errormessage" id="js-server-helpinfo">&nbsp;</span>
			<a href="#">下载网盘</a>	
		</div> <!-- button -->
	</section><!-- content -->
</div>
<!-- container -->


<br><br><br><br>
<div style="text-align:center;">
<p>来源:More Templates <a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a> - Collect from <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a></p>
</div>
</body>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static 'lib/jquery/1.9.1/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/layer/2.4/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'h-ui/js/H-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'h-ui.admin/js/H-ui.admin.js' %}"></script> <!--/_footer 作为公共模版分离出去-->
<script type="text/javascript">
function password_reset(title,url,w,h) {
    layer_show(title,url,w,h)
}


</script>

</html>

templates/order-del-list.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit|ie-comp|ie-stand">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
<!--[if lt IE 9]>
<script type="text/javascript" src="lib/html5shiv.js"></script>
<script type="text/javascript" src="lib/respond.min.js"></script>
<![endif]-->
<link rel="stylesheet" type="text/css" href="{% static 'h-ui/css/H-ui.min.css'%}" />
<link rel="stylesheet" type="text/css" href="{% static 'h-ui.admin/css/H-ui.admin.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'lib/Hui-iconfont/1.0.8/iconfont.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'h-ui.admin/skin/default/skin.css' %}" id="skin" />
<link rel="stylesheet" type="text/css" href="{% static 'h-ui.admin/css/style.css' %}" />
<!--[if IE 6]>
<script type="text/javascript" src="lib/DD_belatedPNG_0.0.8a-min.js" ></script>
<script>DD_belatedPNG.fix('*');</script>
<![endif]-->
<title>用户管理</title>
</head>
<body>
<nav class="breadcrumb"><i class="Hui-iconfont">&#xe67f;</i> 首页 <span class="c-gray en">&gt;</span> 订单管理 <span class="c-gray en">&gt;</span> 删除的订单 <a class="btn btn-success radius r" style="line-height:1.6em;margin-top:3px" href="javascript:location.replace(location.href);" title="刷新" ><i class="Hui-iconfont">&#xe68f;</i></a></nav>
<div class="page-container" style="margin-left:50px;margin-right: 350px">
	<div class="text-c"> 日期范围：
		<input type="text" onfocus="WdatePicker({ maxDate:'#F{$dp.$D(\'datemax\')||\'%y-%M-%d\'}' })" id="datemin" class="input-text Wdate" style="width:120px;">
		-
		<input type="text" onfocus="WdatePicker({ minDate:'#F{$dp.$D(\'datemin\')}',maxDate:'%y-%M-%d' })" id="datemax" class="input-text Wdate" style="width:120px;">
		<input type="text" class="input-text" style="width:250px" placeholder="输入会员名称、电话、邮箱" id="" name="">
		<button type="submit" class="btn btn-success radius" id="" name=""><i class="Hui-iconfont">&#xe665;</i> 搜用户</button>
	</div>
	<div class="cl pd-5 bg-1 bk-gray mt-20"> <span class="l"><a href="javascript:;" onclick="datadel()" class="btn btn-danger radius"><i class="Hui-iconfont">&#xe6e2;</i> 批量删除</a> </span> <span class="r">共有数据：<strong>{{ total }}</strong> 条</span> </div>
	<div class="mt-20">
	<table class="table table-border table-bordered table-hover table-bg table-sort">
		<thead>

			<tr class="text-c">
				<th width="25"><input type="checkbox" name="" value=""></th>
				<th width="250">订单号</th>
				<th width="100">成交客户</th>

				<th width="130">订单成交时间</th>

				<th width="90">订单利润</th>
				<th width="70">订单状态</th>
				<th width="100">操作</th>
			</tr>

		</thead>
		<tbody>
        {% for order in orders %}
			<tr class="text-c">
				<td><input type="checkbox" value="1" name=""></td>
				<td>{{ order.order_id }}</td>
				<td><u style="cursor:pointer" class="text-primary" onclick="member_show('张三','member-show.html','10001','360','400')">{{ order.customer.name }}</u></td>

				<td>{{ order.create_time }}</td>

				<td>${{ order.order_profit }}</td>
                {% if order.order_status == 5 %}
				<td class="td-status"><span class="label label-success radius">{{ order.get_order_status_display }}</span></td>
                {% else %}
                <td class="td-status"><span class="label label-default radius">{{ order.get_order_status_display }}</span></td>
                {% endif %}
				<td class="td-manage"><a style="text-decoration:none" onClick="order_info('详情','{% url 'order:info'%}?order_id={{ order.order_id }}','1000','850')" href="javascript:;" title="详情"><i class="Hui-iconfont">&#xe728;</i></a><a title="还原" href="javascript:;" onclick="order_reduction(this,'{{ order.order_id }}')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe66b;</i></a> <a title="删除" href="javascript:;" onclick="member_del(this,'{{ order.order_id }}')" class="ml-5" style="text-decoration:none"><i class="Hui-iconfont">&#xe6e2;</i></a></td>
			</tr>
        {% endfor %}
		</tbody>
	</table>
	</div>
</div>
<!--_footer 作为公共模版分离出去-->
<script type="text/javascript" src="{% static 'lib/jquery/1.9.1/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/layer/2.4/layer.js' %}"></script>
<script type="text/javascript" src="{% static 'h-ui/js/H-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'h-ui.admin/js/H-ui.admin.js' %}"></script> <!--/_footer 作为公共模版分离出去-->

<!--请在下方写此页面业务相关的脚本-->
<script type="text/javascript" src="{% static 'lib/My97DatePicker/4.8/WdatePicker.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/datatables/1.10.0/jquery.dataTables.min.js' %}"></script>
<script type="text/javascript" src="{% static 'lib/laypage/1.2/laypage.js' %}"></script>
<script type="text/javascript">
$(function(){
	$('.table-sort').dataTable({
		"aaSorting": [[ 1, "desc" ]],//默认第几个排序
		"bStateSave": true,//状态保存
		"aoColumnDefs": [
		  //{"bVisible": false, "aTargets": [ 3 ]} //控制列的隐藏显示
		  {"orderable":false,"aTargets":[0,6]}// 制定列不参与排序
		]
	});

});
/*用户-添加*/
function member_add(title,url,w,h){
	layer_show(title,url,w,h);
}
/*用户-查看*/
function member_show(title,url,id,w,h){
	layer_show(title,url,w,h);
}
/*用户-停用*/
function member_stop(obj,id){
	layer.confirm('确认要停用吗？',function(index){
		$.ajax({
			type: 'POST',
			url: '',
			dataType: 'json',
			success: function(data){
				$(obj).parents("tr").find(".td-manage").prepend('<a style="text-decoration:none" onClick="member_start(this,id)" href="javascript:;" title="启用"><i class="Hui-iconfont">&#xe6e1;</i></a>');
				$(obj).parents("tr").find(".td-status").html('<span class="label label-defaunt radius">已停用</span>');
				$(obj).remove();
				layer.msg('已停用!',{icon: 5,time:1000});
			},
			error:function(data) {
				console.log(data.msg);
			},
		});
	});
}

/*用户-启用*/
function member_start(obj,id){
	layer.confirm('确认要启用吗？',function(index){
		$.ajax({
			type: 'POST',
			url: '',
			dataType: 'json',
			success: function(data){
				$(obj).parents("tr").find(".td-manage").prepend('<a style="text-decoration:none" onClick="member_stop(this,id)" href="javascript:;" title="停用"><i class="Hui-iconfont">&#xe631;</i></a>');
				$(obj).parents("tr").find(".td-status").html('<span class="label label-success radius">已启用</span>');
				$(obj).remove();
				layer.msg('已启用!',{icon: 6,time:1000});
			},
			error:function(data) {
				console.log(data.msg);
			},
		});
	});
}
/*用户-编辑*/
function order_info(title,url,w,h){
	layer_show(title,url,w,h);
}
/*密码-修改*/
function change_password(title,url,id,w,h){
	layer_show(title,url,w,h);
}

/*还原订单*/
    function order_reduction(obj,id) {
        layer.confirm('确认要还原吗？',function(index){

		$.ajax({
			type: 'GET',
			url: '{% url 'order:delete'%}?order_id='+id,
			dataType: 'json',

			success: function(data){


			},
			error:function(data) {
			    console.log('id',id);
				console.log(data.msg);
			},
		});

		layer.close(index);
		layer.msg('已还原!',{icon:1,time:1000});

        setTimeout(function (){
	window.location.reload();
            }, 1200);
	    });
    }
</script>
</body>
</html>